Repository laboratorio-de-praticas-2025-2/Imobiliaria_Bortone, pull requests merged in 2025-09, with the labels that each got.

#194 Feat/devops adiciona metatags
  docs/ManualdeTags.md
  docs/NextConfig.md
  front-end/jsconfig.json
  front-end/next.config.mjs
  front-end/package-lock.json
  front-end/package.json
  front-end/src/app/bem-vindo/page.js
  front-end/src/app/blog/[id]/page.js
  front-end/src/app/blog/page.js
  front-end/src/app/cadastro/page.js
  front-end/src/app/faq/page.js
  front-end/src/app/imoveis/[id]/page.js
  front-end/src/app/imoveis/page.js
  front-end/src/app/layout.js
  front-end/src/app/login/page.js
  front-end/src/app/mapa/page.js
  front-end/src/app/page.js
  front-end/src/app/simulacao/page.js
  front-end/src/components/SEO/Head.js
  front-end/src/config/seo.js
  front-end/src/hooks/useSEO.js
  package-lock.json
Labels: feature

#222 Feature/backend dashboard
  back-end/src/app.js
  back-end/src/controllers/dashboardController.js
  back-end/src/routes/dashboardRoutes.js
  back-end/src/services/dashboardService.js
Labels: feature

#223 docs: algoritmo de recomendacao
  back-end/src/routes/recomendacaoImovelRoutes.js
  documentacao/docs/api/AlgoritmoDeRecomendacao.md
Labels: documentation

#231 Feature/back end mapa
  back-end/src/app.js
  back-end/src/controllers/mapaController.js
  back-end/src/middlewares/validacaoMapa.js
  back-end/src/models/mapaModels.js
  back-end/src/routes/mapaRoutes.js
  back-end/src/services/mapaService.js
  documentacao/docs/api/MapaAPI.md
  documentacao/docs/api/MapaImplementacao.md
  documentacao/docs/api/MapaResumo.md
  documentacao/docs/api/mapa-estrutura.mmd
  documentacao/docs/index.md
  documentacao/mkdocs.yml
Labels: feature

#233 Feature/frontend dashboard
  front-end/package-lock.json
  front-end/package.json
  front-end/src/app/admin/dashboard/page.js
  front-end/src/app/layout.js
  front-end/src/components/dash/Card.js
  front-end/src/components/dash/LineGraph.js
  front-end/src/components/dash/PizzaGraph.js
  front-end/src/styles/dashboard.css
Labels: feature

#285 refactor: refatora as queries do dashboard para usar views
  back-end/src/services/dashboardService.js
Labels: enhancement
