Repository laboratorio-de-praticas-2025-2/Imobiliaria_Bortone, pull requests merged in 2025-08, with the labels that each got.

#43 feat: adiciona sidebar de filtro
  front-end/package-lock.json
  front-end/package.json
  front-end/public/icons/casa.svg
  front-end/public/icons/casa1.ai
  front-end/public/icons/jardim.svg
  front-end/public/icons/murado.svg
  front-end/public/icons/piscina.svg
  front-end/public/icons/terreno.svg
  front-end/src/app/mapa/page.js
  front-end/src/components/SidebarMenu/Location.js
  front-end/src/components/SidebarMenu/LocationButton.js
  front-end/src/components/SidebarMenu/MenuCasa.js
  front-end/src/components/SidebarMenu/MenuTerreno.js
  front-end/src/components/SidebarMenu/MenuWrapper.js
  front-end/src/components/SidebarMenu/Options.js
  front-end/src/components/SidebarMenu/PriceRange.js
  front-end/src/components/SidebarMenu/PropertySize.js
  front-end/src/components/SidebarMenu/PropertyType.js
  front-end/src/components/SidebarMenu/RectangularButton.js
  front-end/src/components/SidebarMenu/RoomsNumber.js
  front-end/src/components/SidebarMenu/SettingsButtons.js
  front-end/src/components/SidebarMenu/SidebarMenu.js
  front-end/src/components/SidebarMenu/SquaredButton.js
  front-end/src/styles/globals.css
Labels: feature

#105 feat: adiciona blog e navegação entre posts
  front-end/public/images/post1.jpeg
  front-end/public/images/post2.jpg
  front-end/public/images/post3.jpg
  front-end/public/images/post4.jpg
  front-end/public/images/post5.jpeg
  front-end/public/images/post6.jpeg
  front-end/public/images/post7.jpeg
  front-end/src/app/blog/[id]/page.js
  front-end/src/app/blog/page.js
  front-end/src/app/layout.js
  front-end/src/components/blog/Cards.js
  front-end/src/components/blog/ContentBlog.js
  front-end/src/components/blog/InputPesquisa.js
  front-end/src/components/blog/ShareButton.js
  front-end/src/constants/posts.js
  front-end/src/styles/blog.css
Labels: enhancement, feature

#113 docs(banco-de-dados): Remove a documentacao de banco de dados
  docs/BancoDeDados.md
  docs/imgs/bd/diagrama.mmd.png
  docs/imgs/bd/exemplo-conexao.png
  docs/imgs/bd/exemplo-select.png
  docs/imgs/bd/imoveis_diagrama.mmd.png
Labels: documentation
